version: "2"

services:
  petclinic:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      

volumes:
  mysql_data:
